# Site settings
title:          Comte
baseurl:        ""
url:            ""

# Google Analytics
google_analytics: UA-154360741-1

# Author
author:
  name:         Mughie Arief
  url:          https://mughieams.com
  email:        mughieams24@gmail.com
  github:       mughieams
  twitter:      mughieams
  instagram:    mughieams
  linkedin:     mughieams


# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-seo-tag
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year/:month/:title

# Pagination settings
pagination:
  enabled: true
  per_page: 3
  permalink: '/page/:num/'
  title: :title
  limit: 0
  sort_field: 'date'
  sort_reverse: true

# Excludes
exclude: [ Gemfile, Gemfile.lock, comte.gemspec ]

# Disqus (Set to your disqus id)
disqus:         jekyll-comte
